target 'MovieCatalogue' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'core', :path => '../core'

  # Pods for MovieCatalogue
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'Reusable'
  pod 'KMPNativeCoroutinesRxSwift'
  pod 'PinLayout'

end
